// Worker entry point. OpenNext builds the Next.js app into .open-next/worker.js;
// this file serves it and adds the cron job that syncs from The Blue Alliance.

// The file only exists after a build, so an error is expected only sometimes.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: generated by `opennextjs-cloudflare build` (untyped, and absent before a build)
import { default as nextHandler } from "./.open-next/worker.js";
import { verifyAccessToken } from "./src/lib/access";
import { tbaConfigured } from "./src/lib/tba/client";
import { handleUpload } from "./src/lib/upload";
import { runScheduledSync, saveSyncStatus } from "./src/lib/tba/sync";

/**
 * POST /admin/api/upload, answered here without Next.js. Sending a request
 * through Next costs more CPU than storing the file, and the Workers Free
 * plan allows 10 ms of CPU per request; big gallery uploads kept hitting it.
 */
async function upload(request: Request, env: CloudflareEnv): Promise<Response> {
  // Only the admin pages themselves may upload (Next checks this for its own forms).
  const origin = request.headers.get("origin");
  if (origin && origin !== new URL(request.url).origin) {
    return Response.json({ error: "Uploads must come from the admin." }, { status: 403 });
  }
  const email = await verifyAccessToken(env, request.headers.get("cf-access-jwt-assertion"));
  if (!email) return Response.json({ error: "Not signed in to the admin." }, { status: 401 });
  return handleUpload(request, env, email);
}

export default {
  async fetch(request, env, ctx) {
    if (request.method === "POST" && new URL(request.url).pathname === "/admin/api/upload") return upload(request, env);
    return nextHandler.fetch(request, env, ctx);
  },

  // Runs on the schedule in wrangler.jsonc ("triggers.crons").
  async scheduled(_controller, env, ctx) {
    if (!tbaConfigured(env)) return;
    ctx.waitUntil(
      runScheduledSync(env).catch((err) =>
        saveSyncStatus(env, "automatic", null, err instanceof Error ? err.message : String(err)),
      ),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
