// Worker entry point. OpenNext builds the Next.js app into .open-next/worker.js;
// this file serves it and adds the cron job that syncs from The Blue Alliance.

// The file only exists after a build, so an error is expected only sometimes.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: generated by `opennextjs-cloudflare build` (untyped, and absent before a build)
import { default as nextHandler } from "./.open-next/worker.js";
import { tbaConfigured } from "./src/lib/tba/client";
import { runScheduledSync, saveSyncStatus } from "./src/lib/tba/sync";

export default {
  fetch: nextHandler.fetch,

  // Runs on the schedule in wrangler.jsonc ("triggers.crons").
  async scheduled(_controller, env, ctx) {
    if (!tbaConfigured(env)) return;
    ctx.waitUntil(
      runScheduledSync(env).catch((err) =>
        saveSyncStatus(env, "automatic", null, err instanceof Error ? err.message : String(err)),
      ),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
