import { getEnv } from "@/lib/cf";

// Streams files out of the R2 media bucket. Keys are generated by the admin
// upload handler, so they are immutable and can be cached forever.
export async function GET(request: Request, ctx: RouteContext<"/media/[...key]">) {
  const { key: parts } = await ctx.params;
  const key = parts.map(decodeURIComponent).join("/");
  if (!key || key.includes("..")) return new Response("Not found", { status: 404 });

  const env = await getEnv();
  const object = await env.MEDIA.get(key, {
    onlyIf: request.headers,
    range: request.headers,
  });
  if (!object) return new Response("Not found", { status: 404 });

  const headers = new Headers();
  object.writeHttpMetadata(headers);
  headers.set("etag", object.httpEtag);
  headers.set("cache-control", "public, max-age=31536000, immutable");
  headers.set("x-content-type-options", "nosniff");
  // Uploaded SVGs and PDFs must never run script on our origin.
  headers.set("content-security-policy", "default-src 'none'; img-src data:; style-src 'unsafe-inline'; sandbox");

  if (!("body" in object) || !object.body) {
    return new Response(null, { status: 304, headers });
  }
  const status = request.headers.has("range") && object.range ? 206 : 200;
  if (status === 206 && object.range && "offset" in object.range && object.range.offset !== undefined) {
    const end = object.range.offset + (object.range.length ?? object.size - object.range.offset) - 1;
    headers.set("content-range", `bytes ${object.range.offset}-${end}/${object.size}`);
  }
  return new Response(object.body, { status, headers });
}
